### ISSUE TITLE
Drop extra configurations

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/cachet-buildpack#2]
We don't need support for:

- `cakephp2`
- `change4`
- `magento`
- `silex`
- `slim`
- `symfony2`
- `yii`
- `yii2`
- `zf1`
- `zf2`

Since we already have a Laravel config.

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by jbrooksuk** [comment]
We'll need to drop Apache on Heroku then :)

**Comment by GrahamCampbell** [comment]
Yeh.

**Comment by jbrooksuk** [comment]
Hopefully this will improve the deploy time, but we'll need to push the changes at the same time for this to work.

Or... I think we can branch it and play that way, without affecting current deploys.
