### ISSUE TITLE
Nginx/Apache

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/cachet-buildpack#3]
Shall we continue using Apache, or should we force Heroku to use nginx? This will allow us to drop the other.

**Comment by GrahamCampbell** [comment]
Just force nginx. :P

**Comment by jbrooksuk** [comment]
We should do that on Cachet then :)

**Comment by jbrooksuk** [comment]
Turns out we're only using nginx by default! Let's remove all references to Apache from the buildpack ;)
