### ISSUE TITLE
Do We Support PHP 5.6.4?

### ISSUE THREAD

**Issue by GrahamCampbell** [cachethq/cachet-buildpack#4]
The readme would suggest otherwise. Also, I think we should only support that version, and drop everything else.

**Comment by jbrooksuk** [comment]
Well the buildpack uses [CHH/php-build](https://github.com/CHH/php-build) which does say it supports 5.6.4 - I'll try make it the default.

**Comment by jbrooksuk** [comment]
I think we're currently using PHP 5.6.2

**Comment by GrahamCampbell** [comment]
Yeh, I know. What happens if we just change that number in the file?

**Comment by jbrooksuk** [comment]
Doesn't work, I had to revert the change.

**Comment by jbrooksuk** [comment]
The original Scalingo buildpack is going to be updated to 5.6.4 today anyway, so I'll see how it's done for next time.

**Comment by GrahamCampbell** [comment]
Cool. :)

**Comment by jbrooksuk** [comment]
Using 5.6.4.
