### ISSUE TITLE
Remove unused extensions

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/cachet-buildpack#5]
What PHP extensions do we not need?

**Comment by GrahamCampbell** [comment]
have you got a list of the ones we currently have?

**Comment by jbrooksuk** [comment]
Nope, but I think it's just:

- `mcrypt`
- `openssl`
- `apcu`

**Comment by GrahamCampbell** [comment]
we're using more than that

**Comment by GrahamCampbell** [comment]
mbstring, json too

**Comment by GrahamCampbell** [comment]
or, rather, if we don't have mbstring, we need it

**Comment by GrahamCampbell** [comment]
we also need readline, pcntl, posix. boris uses them.

**Comment by jbrooksuk** [comment]
We have:

- ext/apcu
- ext/igbinary
- ext/imagick
- ext/libevent
- ext/memcache
- ext/memcached
- ext/mongo
- ext/redis
- ext/sundown
- package-checksum
- package-composer
- package-ext
- package-icu
- package-iq
- package-libmcrypt
- package-memcached
- package-nginx
- package-php

I've not had a full look through, but I assume PHP is compiled with mbstring etc.

**Comment by GrahamCampbell** [comment]
You can remove igbinary, imagick, libevent, memcache, memcached, mongo, redis, sundown.

**Comment by GrahamCampbell** [comment]
We also need those other extensions I listed though. At least until we can finally reach laravel 5.1, where we will be dropping boris. :)

**Comment by GrahamCampbell** [comment]
nb, 5.1 will still ship in may, despite laravel 5.0 being late.
